lib/ticketee_web/router.ex
defmodule TicketeeWeb.Router do
  use TicketeeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TicketeeWeb.Plugs.Auth
    plug TicketeeWeb.Plugs.PreventArchivedUsers
  end

  pipeline :browser_ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TicketeeWeb.Plugs.Auth
    plug TicketeeWeb.Plugs.PreventArchivedUsers
  end

  pipeline :only_logged_in do
    plug TicketeeWeb.Plugs.OnlyLoggedIn
  end

  pipeline :only_admin do
    plug TicketeeWeb.Plugs.OnlyAdmin
  end

  pipeline :jsonapi do
    plug JSONAPI.EnsureSpec
    plug JSONAPI.Deserializer
    plug JSONAPI.UnderscoreParameters
  end

  pipeline :api_logged_in do
    plug TicketeeWeb.Plugs.APIAuth
  end

  # All users (including those not logged in)
  scope "/", TicketeeWeb do
    pipe_through :browser

    resources "/accounts", AccountController, only: [:new, :create]
    resources "/sessions", SessionController, singleton: true, only: [:new, :create, :delete]
  end

  # Admin users
  scope "/", TicketeeWeb do
    pipe_through [:browser, :only_admin]

    get "/admin", PageController, :admin_index

    resources "/projects", ProjectController, only: [:new, :create, :delete]

    resources "/users", UserController, only: [:index, :new, :create]
    patch "/users/:id/promote", UserController, :promote
    patch "/users/:id/archive", UserController, :archive

    get "/users/:user_id/roles", UserRoleController, :show

    resources "/states", StateController, only: [:index, :new, :create, :edit, :update, :delete]
    patch "/states/:id/default", StateController, :make_default
  end

  # Admin users - AJAX support routes
  scope "/", TicketeeWeb do
    pipe_through [:browser_ajax, :only_admin]

    post "/users/:user_id/roles", UserRoleController, :create
    delete "/users/:user_id/roles/:project_id", UserRoleController, :delete
  end

  # Logged in users
  scope "/", TicketeeWeb do
    pipe_through [:browser, :only_logged_in]

    get "/", ProjectController, :index

    # "My Account" routes
    resources "/account", AccountController, singleton: true, only: [:show, :edit, :update]

    resources "/projects", ProjectController, only: [:index, :show, :edit, :update] do
      resources "/tickets", TicketController, except: [:index]
    end

    get "/tickets/search", TicketSearchController, :index

    resources "/tickets", TicketController, only: [] do
      resources "/comments", CommentController, only: [:index, :create, :edit, :update, :delete]
      resources "/tags", TagController, only: [:index, :create, :delete]
      resources "/watcher", TicketWatcherController, only: [:create, :delete],
        as: :watcher, singleton: true

      resources "/attachments", TicketAttachmentController,
        as: :attachment, only: [:show, :new, :create, :delete]
    end
  end

  # API Sessions
  scope "/api", TicketeeWeb.API, as: :api do
    pipe_through [:jsonapi]

    post "/sessions", SessionController, :create
  end

  # JSON-API
  scope "/api", TicketeeWeb.API, as: :api do
    pipe_through [:api_logged_in, :jsonapi]

    get "/account", AccountController, :show

    resources "/projects", ProjectController, only: [:index, :show] do
      get "/tickets", TicketController, :index_for_project
    end

    resources "/tickets", TicketController, only: [:index, :show] do
      resources "/comments", CommentController, only: [:index]
    end

    resources "/comments", CommentController, only: [:show]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TicketeeWeb.Telemetry
    end
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/ticketee/projects/ticket.ex
defmodule Ticketee.Projects.Ticket do
  use Ecto.Schema
  import Ecto.Changeset

  alias Ticketee.Projects.{Project, State}
  alias Ticketee.Accounts.User
  alias Ticketee.Tags.Tag

  schema "tickets" do
    field :title, :string
    field :description, :string
    field :comment_count, :integer, default: 0

    belongs_to :project, Project
    belongs_to :author, User, type: :binary_id
    belongs_to :state, State
    many_to_many :tags, Tag, join_through: "ticket_tags"

    timestamps(type: :utc_datetime)
  end

  def changeset(ticket, attrs) do
    ticket
    |> cast(attrs, [:title, :description])
    |> validate_required([:title, :description])
    |> validate_length(:title, max: 255)
    |> assoc_constraint(:project)
  end

  def state_changeset(ticket, attrs) do
    ticket
    |> cast(attrs, [:state_id])
    |> assoc_constraint(:state)
  end
end

lib/ticketee_web/controllers/api/ticket_controller.ex
defmodule TicketeeWeb.API.TicketController do
  use TicketeeWeb, :controller
  import TicketeeWeb.API.ControllerHelpers, only: [resp_with_error_status: 3]
  import TicketeeWeb.API.ProjectController, only: [set_project: 2]

  alias Ticketee.Authorize
  alias Ticketee.Projects

  plug :set_project, [param_key: "project_id"] when action in ~w(index_for_project)a
  plug :authorize_for_project when action in ~w(index_for_project)a

  plug :set_ticket when action in ~w(show)a
  plug :authorize_for_ticket when action in ~w(show)a

  def index(conn, params) do
    current_user = conn.assigns.current_user
    search_params = Map.get(params, "filter", %{})

    tickets = Authorize.search_tickets_for(current_user, search_params)
      |> preload_ticket_associations()

    render(conn, "show.json", %{data: tickets})
  end

  def index_for_project(conn, _params) do
    project = conn.assigns.project
    tickets = Projects.list_tickets_for_index(project)
      |> preload_ticket_associations()

    render(conn, "show.json", %{data: tickets})
  end

  def show(conn, _params) do
    ticket = conn.assigns.ticket
      |> preload_ticket_associations()

    render(conn, "show.json", %{data: ticket})
  end

  ## Helpers

  defp preload_ticket_associations(ticket_or_tickets) do
    ticket_or_tickets
    |> Projects.with_ticket_project()
    |> Projects.with_ticket_author()
    |> Projects.with_state()
    |> Projects.with_ticket_tags()
  end

  def set_ticket(conn, opts) do
    param_key = Keyword.get(opts, :param_key, "id")
    ticket_id = conn.params[param_key]
    ticket = ticket_id && Projects.get_ticket(ticket_id)

    if ticket do
      assign(conn, :ticket, ticket)
    else
      conn
      |> resp_with_error_status(:not_found, "Ticket not found")
      |> halt()
    end
  end

  defp authorize_for_project(conn, _opts) do
    %{current_user: current_user,
      project: project} = conn.assigns

    if Authorize.allowed?(current_user, :show, project) do
      conn
    else
      conn
      |> resp_with_error_status(:forbidden, Authorize.not_authorized_message())
      |> halt()
    end
  end

  defp authorize_for_ticket(conn, _opts) do
    %{current_user: current_user,
      ticket: ticket} = conn.assigns

    if Authorize.allowed?(current_user, :show, ticket) do
      conn
    else
      conn
      |> resp_with_error_status(:forbidden, Authorize.not_authorized_message())
      |> halt()
    end

  end
end

lib/ticketee_web/controllers/ticket_controller.ex
defmodule TicketeeWeb.TicketController do
  use TicketeeWeb, :controller
  import TicketeeWeb.ProjectController, only: [set_project: 2, cache_project_role: 2]

  alias Ticketee.Projects
  alias Ticketee.Projects.Ticket
  alias Ticketee.Attachments
  alias Ticketee.Authorize
  alias Ticketee.Notifications.Watchers
  alias TicketeeWeb.Notifications

  @ticket_not_found_message "The ticket you were looking for could not be found!"

  plug :set_project, param_key: "project_id"
  plug :set_ticket when action in ~w(show edit update delete)a
  plug :cache_project_role when action in ~w(show)a
  plug :authorize_for_ticket

  def show(conn, _params) do
    current_user = conn.assigns.current_user
    project = conn.assigns.project
    ticket = conn.assigns.ticket
      |> Projects.with_ticket_author()
      |> Projects.with_state()
      |> Projects.with_ticket_tags()

    watcher = Watchers.get_ticket_watcher(ticket, current_user)
    attachments = Attachments.attachments_for(ticket)

    conn
    |> set_title("Ticketee | Tickets | #{project.name} - #{ticket.title}")
    |> render("show.html", ticket: ticket, watcher: watcher, attachments: attachments)
  end

  def new(conn, _params) do
    project = conn.assigns.project
    changeset = Projects.change_ticket_for(project, %{})

    render(conn, "new.html", project: project, changeset: changeset)
  end

  def create(conn, %{"ticket" => ticket_params}) do
    current_user = conn.assigns.current_user
    project = conn.assigns.project

    case Projects.create_ticket_with_default_state_for(current_user, project, ticket_params) do
      {:ok, ticket} ->
        conn
        |> Notifications.add_ticket_watcher(ticket)
        |> put_flash(:info, "Ticket has been successfully created!")
        |> redirect(to: Routes.project_ticket_path(conn, :show, project, ticket))

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Failed to create ticket!")
        |> render("new.html", project: project, changeset: changeset)
    end
  end

  def edit(conn, _params) do
    ticket = conn.assigns.ticket
    changeset = Projects.change_ticket(ticket, %{})

    render(conn, "edit.html", changeset: changeset)
  end

  def update(conn, %{"ticket" => ticket_params}) do
    %{project: project, ticket: ticket} = conn.assigns

    case Projects.update_ticket(ticket, ticket_params) do
      {:ok, ticket} ->
        conn
        |> put_flash(:info, "Ticket has been successfully updated!")
        |> redirect(to: Routes.project_ticket_path(conn, :show, project, ticket))

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Failed to update ticket!")
        |> render("edit.html", project: project, changeset: changeset)
    end
  end

  def delete(conn, _params) do
    %{project: project, ticket: ticket} = conn.assigns

    case Projects.delete_ticket(ticket) do
      {:ok, _ticket} ->
        conn
        |> put_flash(:info, "Ticket has been successfully deleted!")
        |> redirect(to: Routes.project_path(conn, :show, project))

      {:error, _changeset} ->
        conn
        |> put_flash(:error, "Failed to delete ticket!")
        |> redirect(to: Routes.project_ticket_path(conn, :show, project, ticket))
    end
  end

  ## Helpers

  defp set_ticket(conn, _opts) do
    ticket_id = conn.params["id"]
    project = conn.assigns.project

    ticket = ticket_id && Projects.get_ticket_for(project, ticket_id)

    if ticket do
      assign(conn, :ticket, ticket)
    else
      redirect_not_found(conn)
    end

  rescue
    Ecto.Query.CastError ->
      # When `params["id"]` cannot be cast to integer, also redirect
      redirect_not_found(conn)
  end

  defp authorize_for_ticket(conn, _opts) do
    %{current_user: current_user,
      project: project} = conn.assigns

    ticket = conn.assigns[:ticket] || Ticket
    action = action_name(conn)

    if Authorize.allowed?(current_user, action, {project, ticket}) do
      conn
    else
      conn
      |> put_flash(:error, Authorize.not_authorized_message())
      |> redirect(to: Routes.project_path(conn, :show, project))
      |> halt()
    end
  end

  defp redirect_not_found(conn, _opts \\ []) do
    project = conn.assigns.project

    conn
    |> put_flash(:error, @ticket_not_found_message)
    |> redirect(to: Routes.project_path(conn, :show, project))
    |> halt()
  end
end

lib/ticketee_web/views/ticket_view.ex
defmodule TicketeeWeb.TicketView do
  use TicketeeWeb, :view
  import TicketeeWeb.StateView, only: [search_state_badge: 2]
  import TicketeeWeb.TagView, only: [search_tag_badge: 2]
  import TicketeeWeb.TicketAttachmentView, only: [
      attachment_path: 2,
      attachment_preview_img: 2,
    ]

  alias Ticketee.Attachments
  alias Ticketee.Attachments.TicketAttachment
  alias Ticketee.Projects.Comment
  alias Ticketee.Tags.Tag
  alias Ticketee.Notifications.TicketWatcher

  def ticket_author(%{author: %{email: email}}) do
    email
  end

  def ticket_author(_other) do
    "N/A"
  end

  def ticket_created_at(%{inserted_at: inserted_at = %DateTime{}}) do
    timestamp = DateTime.truncate(inserted_at, :second)
    time_ago = time_ago_in_words(timestamp)

    "#{DateTime.to_string(timestamp)} (#{time_ago})"
  end

  def ticket_created_at(_other) do
    "N/A"
  end
end

lib/ticketee_web/templates/ticket/_form.html.eex
<%= form_for @changeset, @path, [method: @form_method], fn f -> %>
  <div class="form-group">
    <%= label f, :title, class: "form-label" %>
    <%= bootstrap_text_input f, :title, required: true %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "form-label" %>
    <%= bootstrap_textarea f, :description, required: true %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-actions">
    <%= submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

lib/ticketee_web/templates/ticket/edit.html.eex
<header class="page-header">
  <h1>Edit Ticket "<%= @ticket.title %>"</h1>
</header>

<%= render("_form.html", Map.merge(assigns, %{
      path: Routes.project_ticket_path(@conn, :update, @project, @ticket),
      form_method: "patch",
    })) %>

lib/ticketee_web/templates/ticket/new.html.eex
<header class="page-header">
  <h1>New Ticket for "<%= @project.name %>"</h1>
</header>

<%= render("_form.html", Map.merge(assigns, %{
      path: Routes.project_ticket_path(@conn, :create, @project),
      form_method: "post",
    })) %>

lib/ticketee_web/templates/ticket/show.html.eex
<p><%= link "Back", to: Routes.project_path(@conn, :show, @project) %></p>

<header class="page-header">
  <div class="title-group">
    <h1 class="ticket-title">
      <%= @ticket.title %>
    </h1>

    <h2 class="project-name">
      <%= link @project.name, to: Routes.project_path(@conn, :show, @project) %>
    </h2>
  </div>

  <div class="actions" role="group" aria-label="Ticket actions">
    <%= if allowed?(@current_user, :index, {@ticket, Comment}) do %>
      <%= link "Comments (#{@ticket.comment_count})", to: Routes.ticket_comment_path(@conn, :index, @ticket), class: "link-comments" %>
    <% end %>


    <%= if allowed?(@current_user, :index, {@ticket, Tag}) do %>
      <%= link "Tags", to: Routes.ticket_tag_path(@conn, :index, @ticket), class: "link-tags" %>
    <% end %>

    <%= if @watcher do %>
      <%= if allowed?(@current_user, :delete, {@ticket, TicketWatcher}) do %>
        <%= link "Unwatch", to: Routes.ticket_watcher_path(@conn, :delete, @ticket),
              class: "link-unwatch", method: :delete %>
      <% end %>
    <% else %>
      <%= if allowed?(@current_user, :create, {@ticket, TicketWatcher}) do %>
        <%= link "Watch", to: Routes.ticket_watcher_path(@conn, :create, @ticket),
              class: "link-watch", method: :post %>
      <% end %>
    <% end %>

    <%= if allowed?(@current_user, :update, {@project, @ticket}) do %>
      <%= link "Edit", to: Routes.project_ticket_path(@conn, :edit, @project, @ticket), class: "link-edit" %>
    <% end %>
    <%= if allowed?(@current_user, :delete, {@project, @ticket}) do %>
      <%= link "Delete", to: Routes.project_ticket_path(@conn, :delete, @project, @ticket), class: "link-delete",
            method: :delete, data: [confirm: "Are you sure?"] %>
    <% end %>
  </div>
</header>

<section class="container">
  <div class="ticket-description">
    <%= text_to_html(@ticket.description) %>
  </div>

  <table id="ticket-attributes" class="table">
    <tbody>
      <tr>
        <th scope="row">Author</th>
        <td class="author-info"><%= ticket_author(@ticket) %></td>
      </tr>
      <tr>
        <th scope="row">Created At</th>
        <td class="created-at-info"><%= ticket_created_at(@ticket) %></td>
      </tr>
      <%= if @ticket.state do %>
        <tr>
          <th scope="row">State</th>
          <td class="state"><%= search_state_badge(@conn, @ticket.state) %></td>
        </tr>
      <% end %>
      <%= if Enum.any?(@ticket.tags) do %>
        <tr>
          <th scope="row">Tags</th>
          <td class="tags">
            <%= for tag <- @ticket.tags do %>
              <%= search_tag_badge(@conn, tag) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

<section class="container">
  <header class="page-header">
    <h2>Attachments</h2>

    <div class="actions" role="group" aria-label="Attachment actions">
      <%= if allowed?(@current_user, :create, {@ticket, TicketAttachment}) do %>
        <%= link "New Attachment", to: Routes.ticket_attachment_path(@conn, :new, @ticket), class: "link-add" %>
      <% end %>
    </div>
  </header>

  <div class="ticket-attachment-container">
    <%= for attachment <- @attachments do %>
      <article class="card">
        <%= attachment_preview_img(@conn, attachment) %>
        <div class="card-body">
          <h4 class="card-title">
            <%= link attachment.file, to: attachment_path(@conn, attachment) %>
            <span class="attachment-size">(<%= Attachments.file_size_description(attachment.size) %>)</span>

            <%= if allowed?(@current_user, :delete, {@ticket, attachment}) do %>
              <%= link "Delete", to: attachment_path(@conn, attachment), class: "link-delete",
                    method: :delete, data: [confirm: "Are you sure you want to delete this attachment?"] %>
            <% end %>
          </h4>
          <%= if attachment.description do %>
            <%= text_to_html(attachment.description, attributes: [class: "card-text"]) %>
          <% end %>
        </div>
      </article>
    <% end %>
    <%= if Enum.empty?(@attachments) do %>
      <p>No attachments currently</p>
    <% end %>
  </div>
</section>