lib/ticketee_web/router.ex
defmodule TicketeeWeb.Router do
  use TicketeeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TicketeeWeb.Plugs.Auth
    plug TicketeeWeb.Plugs.PreventArchivedUsers
  end

  pipeline :browser_ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TicketeeWeb.Plugs.Auth
    plug TicketeeWeb.Plugs.PreventArchivedUsers
  end

  pipeline :only_logged_in do
    plug TicketeeWeb.Plugs.OnlyLoggedIn
  end

  pipeline :only_admin do
    plug TicketeeWeb.Plugs.OnlyAdmin
  end

  pipeline :jsonapi do
    plug JSONAPI.EnsureSpec
    plug JSONAPI.Deserializer
    plug JSONAPI.UnderscoreParameters
  end

  pipeline :api_logged_in do
    plug TicketeeWeb.Plugs.APIAuth
  end

  # All users (including those not logged in)
  scope "/", TicketeeWeb do
    pipe_through :browser

    resources "/accounts", AccountController, only: [:new, :create]
    resources "/sessions", SessionController, singleton: true, only: [:new, :create, :delete]
  end

  # Admin users
  scope "/", TicketeeWeb do
    pipe_through [:browser, :only_admin]

    get "/admin", PageController, :admin_index

    resources "/projects", ProjectController, only: [:new, :create, :delete]

    resources "/users", UserController, only: [:index, :new, :create]
    patch "/users/:id/promote", UserController, :promote
    patch "/users/:id/archive", UserController, :archive

    get "/users/:user_id/roles", UserRoleController, :show

    resources "/states", StateController, only: [:index, :new, :create, :edit, :update, :delete]
    patch "/states/:id/default", StateController, :make_default
  end

  # Admin users - AJAX support routes
  scope "/", TicketeeWeb do
    pipe_through [:browser_ajax, :only_admin]

    post "/users/:user_id/roles", UserRoleController, :create
    delete "/users/:user_id/roles/:project_id", UserRoleController, :delete
  end

  # Logged in users
  scope "/", TicketeeWeb do
    pipe_through [:browser, :only_logged_in]

    get "/", ProjectController, :index

    # "My Account" routes
    resources "/account", AccountController, singleton: true, only: [:show, :edit, :update]

    resources "/projects", ProjectController, only: [:index, :show, :edit, :update] do
      resources "/tickets", TicketController, except: [:index]
    end

    get "/tickets/search", TicketSearchController, :index

    resources "/tickets", TicketController, only: [] do
      resources "/comments", CommentController, only: [:index, :create, :edit, :update, :delete]
      resources "/tags", TagController, only: [:index, :create, :delete]
      resources "/watcher", TicketWatcherController, only: [:create, :delete],
        as: :watcher, singleton: true

      resources "/attachments", TicketAttachmentController,
        as: :attachment, only: [:show, :new, :create, :delete]
    end
  end

  # API Sessions
  scope "/api", TicketeeWeb.API, as: :api do
    pipe_through [:jsonapi]

    post "/sessions", SessionController, :create
  end

  # JSON-API
  scope "/api", TicketeeWeb.API, as: :api do
    pipe_through [:api_logged_in, :jsonapi]

    get "/account", AccountController, :show

    resources "/projects", ProjectController, only: [:index, :show] do
      get "/tickets", TicketController, :index_for_project
    end

    resources "/tickets", TicketController, only: [:index, :show] do
      resources "/comments", CommentController, only: [:index]
    end

    resources "/comments", CommentController, only: [:show]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TicketeeWeb.Telemetry
    end
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/ticketee_web/views/layout_view.ex
defmodule TicketeeWeb.LayoutView do
  use TicketeeWeb, :view

  def nav_link(conn, text, opts) do
    opts = add_nav_link_opts(opts, conn.request_path, opts[:to])
    link(text, opts)
  end

  defp add_nav_link_opts(opts, current_path, current_path) do
    [{:class, "nav-link active"}, {"aria-current", "page"} | opts]
  end

  defp add_nav_link_opts(opts, _, _) do
    [{:class, "nav-link"} | opts]
  end
end

lib/ticketee_web/templates/layout/_navbar.html.eex
<nav role="navigation" class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link "Ticketee", to: Routes.project_path(@conn, :index), class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-main-container" aria-controls="navbar-main-container" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <section class="navbar-collapse collapse" id="navbar-main-container">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= nav_link @conn, "Projects", to: Routes.project_path(@conn, :index) %>
        </li>
        <li class="nav-item">
          <%= nav_link @conn, "Search Tickets", to: Routes.ticket_search_path(@conn, :index) %>
        </li>
        <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
          <li class="nav-item">
            <%= nav_link @conn, "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %>
          </li>
        <% end %>
      </ul>

      <ul class="navbar-nav mb-2 mb-md-0">
        <%= if @conn.assigns[:current_user] do %>
          <%= if admin?(@conn.assigns[:current_user]) do %>
            <li class="nav-item">
              <%= nav_link @conn, "Admin Area", to: Routes.page_path(@conn, :admin_index), class: "nav-link link-admin" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link @current_user.email, to: Routes.account_path(@conn, :show), class: "signed-in-user" %>
          </li>
          <li class="nav-item">
            <%= nav_link @conn, "Sign out", to: Routes.session_path(@conn, :delete), method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= nav_link @conn, "Sign in", to: Routes.session_path(@conn, :new) %>
          </li>
          <li class="nav-item">
            <%= nav_link @conn, "Sign up", to: Routes.account_path(@conn, :new) %>
          </li>
        <% end %>
      </ul>
    </section>
  </div>
</nav>

lib/ticketee_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= Map.get(assigns, :page_title, "Ticketee") %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header class="main-header">
      <%= render "_navbar.html", assigns %>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/ticketee_web/templates/layout/email.html.eex
<!DOCTYPE html>
<html>
<head>
  <title>Ticketee</title>
  <link rel="stylesheet" type="text/css" href="<%= Routes.static_url(TicketeeWeb.Endpoint, "/email_assets/email.css") %>">
</head>
<body>
  <%= @inner_content %>
</body>
</html>