lib/ticketee_web/router.ex
defmodule TicketeeWeb.Router do
  use TicketeeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TicketeeWeb.Plugs.Auth
    plug TicketeeWeb.Plugs.PreventArchivedUsers
  end

  pipeline :browser_ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TicketeeWeb.Plugs.Auth
    plug TicketeeWeb.Plugs.PreventArchivedUsers
  end

  pipeline :only_logged_in do
    plug TicketeeWeb.Plugs.OnlyLoggedIn
  end

  pipeline :only_admin do
    plug TicketeeWeb.Plugs.OnlyAdmin
  end

  pipeline :jsonapi do
    plug JSONAPI.EnsureSpec
    plug JSONAPI.Deserializer
    plug JSONAPI.UnderscoreParameters
  end

  pipeline :api_logged_in do
    plug TicketeeWeb.Plugs.APIAuth
  end

  # All users (including those not logged in)
  scope "/", TicketeeWeb do
    pipe_through :browser

    resources "/accounts", AccountController, only: [:new, :create]
    resources "/sessions", SessionController, singleton: true, only: [:new, :create, :delete]
  end

  # Admin users
  scope "/", TicketeeWeb do
    pipe_through [:browser, :only_admin]

    get "/admin", PageController, :admin_index

    resources "/projects", ProjectController, only: [:new, :create, :delete]

    resources "/users", UserController, only: [:index, :new, :create]
    patch "/users/:id/promote", UserController, :promote
    patch "/users/:id/archive", UserController, :archive

    get "/users/:user_id/roles", UserRoleController, :show

    resources "/states", StateController, only: [:index, :new, :create, :edit, :update, :delete]
    patch "/states/:id/default", StateController, :make_default
  end

  # Admin users - AJAX support routes
  scope "/", TicketeeWeb do
    pipe_through [:browser_ajax, :only_admin]

    post "/users/:user_id/roles", UserRoleController, :create
    delete "/users/:user_id/roles/:project_id", UserRoleController, :delete
  end

  # Logged in users
  scope "/", TicketeeWeb do
    pipe_through [:browser, :only_logged_in]

    get "/", ProjectController, :index

    # "My Account" routes
    resources "/account", AccountController, singleton: true, only: [:show, :edit, :update]

    resources "/projects", ProjectController, only: [:index, :show, :edit, :update] do
      resources "/tickets", TicketController, except: [:index]
    end

    get "/tickets/search", TicketSearchController, :index

    resources "/tickets", TicketController, only: [] do
      resources "/comments", CommentController, only: [:index, :create, :edit, :update, :delete]
      resources "/tags", TagController, only: [:index, :create, :delete]
      resources "/watcher", TicketWatcherController, only: [:create, :delete],
        as: :watcher, singleton: true

      resources "/attachments", TicketAttachmentController,
        as: :attachment, only: [:show, :new, :create, :delete]
    end
  end

  # API Sessions
  scope "/api", TicketeeWeb.API, as: :api do
    pipe_through [:jsonapi]

    post "/sessions", SessionController, :create
  end

  # JSON-API
  scope "/api", TicketeeWeb.API, as: :api do
    pipe_through [:api_logged_in, :jsonapi]

    get "/account", AccountController, :show

    resources "/projects", ProjectController, only: [:index, :show] do
      get "/tickets", TicketController, :index_for_project
    end

    resources "/tickets", TicketController, only: [:index, :show] do
      resources "/comments", CommentController, only: [:index]
    end

    resources "/comments", CommentController, only: [:show]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TicketeeWeb.Telemetry
    end
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/ticketee_web/controllers/ticket_search_controller.ex
defmodule TicketeeWeb.TicketSearchController do
  use TicketeeWeb, :controller

  alias Ticketee.Authorize
  alias Ticketee.Projects
  alias Ticketee.Tags

  plug :set_search_options

  def index(conn, params) do
    current_user = conn.assigns.current_user
    search_params = Map.get(params, "search", %{})

    tickets = Authorize.search_tickets_for(current_user, search_params)
      |> Projects.with_ticket_author()
      |> Projects.with_ticket_tags()
      |> with_preloaded_search_associations(conn.assigns)

    render(conn, "search.html", tickets: tickets, search_params: search_params)
  end

  defp set_search_options(conn, _opts) do
    conn
    |> assign(:projects, Projects.list_projects_for_search())
    |> assign(:states, Projects.list_states())
    |> assign(:tags, Tags.list_tags())
  end

  defp with_preloaded_search_associations(tickets,
                                          %{projects: projects,
                                            states: states}) do
    indexed_projects = Enum.into(projects, %{}, &({&1.id, &1}))
    indexed_states = Enum.into(states, %{}, &({&1.id, &1}))

    Enum.map(tickets, fn ticket ->
      %{ticket | project: indexed_projects[ticket.project_id],
                 state: indexed_states[ticket.state_id]}
    end)
  end
end

lib/ticketee_web/views/ticket_search_view.ex
defmodule TicketeeWeb.TicketSearchView do
  use TicketeeWeb, :view
  import TicketeeWeb.TicketView, only: [ticket_author: 1]
  import TicketeeWeb.StateView, only: [search_state_badge: 2]
  import TicketeeWeb.TagView, only: [search_tag_badge: 2]

  def project_search_options(projects) do
    Enum.map(projects, fn project -> {project.name, Phoenix.Param.to_param(project)} end)
  end

  def state_search_options(states) do
    Enum.map(states, fn state -> state.name end)
  end

  def tag_search_options(tags) do
    Enum.map(tags, fn tag -> tag.name end)
  end
end

lib/ticketee_web/templates/ticket_search/search.html.eex
<header class="page-header">
  <h1>Search tickets</h1>
</header>

<section class="container">
  <%= form_for @conn, Routes.ticket_search_path(@conn, :index), [as: :search, method: :get], fn f -> %>
    <div class="form-group">
      <%= label f, :project_id, "Project", class: "form-label" %>
      <%= select f, :project_id, project_search_options(@projects), class: "form-select",
            prompt: "Any Project", selected: @search_params["project_id"] %>
    </div>

    <div class="form-group">
      <%= label f, :ticket_title, "Title", class: "form-label" %>
      <%= bootstrap_text_input f, :ticket_title, value: @search_params["ticket_title"] %>
    </div>

    <div class="form-group">
      <%= label f, :state_name, "State", class: "form-label" %>
      <%= select f, :state_name, state_search_options(@states), class: "form-select",
            prompt: "Any state", selected: @search_params["state_name"] %>
    </div>

    <div class="form-group">
      <%= label f, :tag_name, "Tag", class: "form-label" %>
      <%= select f, :tag_name, tag_search_options(@tags), class: "form-select",
            prompt: "Any tag", selected: @search_params["tag_name"] %>
    </div>

    <div class="form-actions">
      <%= submit "Search", class: "btn btn-primary" %>
    </div>
  <% end %>

  <table class="table tickets-table">
    <thead>
      <tr>
        <th scope="col">Project</th>
        <th scope="col">Title</th>
        <th scope="col">State</th>
        <th scope="col">Author</th>
        <th scope="col">Description</th>
        <th scope="col">Tags</th>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <%= for ticket <- @tickets do %>
        <tr class="ticket-row">
          <td class="ticket-project">
            <%= link ticket.project.name, to: Routes.project_path(@conn, :show, ticket.project) %>
          </td>
          <td class="ticket-title">
            <%= link ticket.title, to: Routes.project_ticket_path(@conn, :show, ticket.project, ticket) %>
          </td>
          <td class="ticket-state"><%= search_state_badge(@conn, ticket.state) %></td>
          <td class="ticket-author"><%= ticket_author(ticket) %></td>
          <td class="ticket-description"><%= ticket.description %></td>
          <td class="ticket-tags">
            <%= for tag <- ticket.tags do %>
              <%= search_tag_badge(@conn, tag) %>
            <% end %>
          </td>
        </tr>
      <% end %>
      <%= if Enum.empty?(@tickets) do %>
        <tr>
          <td colspan="6">No tickets found.</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>